### ISSUE TITLE
Python 3.2 compatibility

### ISSUE THREAD

**Issue by zfriedl** [mgood/jprops#13]
Jprops breaks on python 3.2.
```
Python 3.2.3 (default, Feb 20 2013, 14:44:27) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jprops
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.2/dist-packages/jprops.py", line 155
    c = u'\\\\'
              ^
SyntaxError: invalid syntax
```

**Comment by mgood** [comment]
Yeah, as mentioned in the README, jprops works with 2.6, 2.7, or 3.3 (or higher). Python 3.3 added back the [unicode literal support](https://www.python.org/dev/peps/pep-0414/) in order to simplify porting code to Python 3, so this library currently expects that.

Can you upgrade your Python installation?

**Comment by zfriedl** [comment]
Yeah, I saw the readme, still I opened the issue.
If a script needs to be running on multiple servers with mixed environments, some of them with python 3.4, some with 3.2, this issue is quite a headache. Upgrade is not an option, I know there are other ways to get a python3.4, but that's not the question here. I am suggesting that jprops should avoid those unicode literals... ;)

**Comment by mgood** [comment]
Well, Python 3.3 added back support for the `u` prefix because it makes it much easier to maintain code that is compatible with both Python 2 and 3.

The unicode literals only appear a few times in jprops.py itself, so if you only need to run on Python 3 you could make a copy to include with your code and remove the `u` prefixes.

They appear more times throughout the tests, so changing the whole codebase to be 3.2 compatible would require more work. I'm not really using jprops much at this time, so given the age and adoption rate of Python 3.2 it's not something I'm likely to work on.
