### ISSUE TITLE
Incorrect encoding for special characters

### ISSUE THREAD

**Issue by reinaldo13** [mgood/jprops#14]
The `_unescape` method within `jprops.py` incorrectly encodes special charecters such as `é`.
The correct encoding for `é` is `\u00e9`, however, `_unescape` returns `\u00c3\u00a9`

**Comment by mgood** [comment]
So, it looks like the character was encoded as utf-8 in the file. However, based on the [Java properties documentation](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html#load-java.io.InputStream-), they need to be either encoded as latin-1, or using `\u` for the Unicode escape sequence in the file itself:
> Characters not in Latin1, and certain special characters, are represented in keys and elements using Unicode escapes

How was the file written? Was the `é` added manually, or was it written by a library?

**Comment by reinaldo13** [comment]
Hi @mgood. Thanks for replying! The file was created by a third party company, and it looks like the `é` was added manually. So you are absolutely right, based on the Java Properties Docs, the file should either be `lating-1` or use `/u` for escaping special characters like the one in question. To avoid confusion I suggest one of the following options:

1- Add a link to the Java Properties Docs to the jprops docs.
2.- Allow passing an optional parameter that tells jprops the type of encoding used to write the property file (if different than `latin-1`)

What do you think?
BTW, thanks for maintaining jprops. Great work!

**Comment by mgood** [comment]
I haven't been using this library myself recently, but I was thinking about this since some other people have asked about it as well. On taking another look at the Java documentation, the `latin-1` encoding applies to files access as a byte-oriented stream, but they do also support the text-based `Reader` and `Writer` interfaces which can support other text encodings. This is similar to how I was thinking of approaching it, so I rewrote the internals of this to be able to support text-oriented file interfaces such as returned by `io.open(name, encoding='utf-8')` (or [io.TextIOBase](https://docs.python.org/3.6/library/io.html#io.TextIOBase)).

There are more details in the README.
