### ISSUE TITLE
Not all file modes work with jprops.load_properties (Python3)

### ISSUE THREAD

**Issue by paulmueller** [mgood/jprops#19]
The `jprops.load_properties` method takes a "readable file-like" object `fh`.
In Windows Python 3.5.2 (Anaconda 4.2), this only works with the "rbU" mode:

``` python
with open(file_name, "rbU") as fh:
        prop = jprops.load_properties(fh)
```

Other modes give:
- "rU": `TypeError: cannot use a bytes pattern on a string-like object` (jprops line 256)
- "r": `TypeError: Can't convert 'bytes' object to str implicitly` (jprops line 248)

Opening with `codecs.open(..., encoding="utf-8")` also does not work. Not sure whether this might be important for Python2.

**Comment by mgood** [comment]
Sorry for the delay. This was mentioned in the more detailed docs on the site. It was previously written to support the format in the Java documentation for byte streams. So, the `b` was necessary in the mode on Python 3 to open files in binary mode.

However, I just released a 2.0 version that rewrote a bunch of things to support files opened with other text encodings. I discussed it in more detail on #14, or see the updated README for docs.

The `U` in the mode isn't necessary, since jprops already handles translating any newlines. For writing you can pass the `newline` arg to `open()` to translate newlines written to the file. On Python 2 I would recommend using `io.open` instead of `codecs.open` since it has better compatibility with the Python 3 `open` built-in.
